trigger:
- master

jobs:
  - job: ktlint
    timeoutInMinutes: 15
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'ktlint'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false
  - job: detekt
    timeoutInMinutes: 15
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'detekt'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false
  - job: lint
    timeoutInMinutes: 15
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'lintDebug'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false
  - job: build
    timeoutInMinutes: 15
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'assembleDebug'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false
  - job: unitTests
    timeoutInMinutes: 15
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        options: '--console plain -Pcoverage=true'
        tasks: 'testDebug'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        gradleOptions: '-Xmx3072m'
        sonarQubeRunAnalysis: false
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'JaCoCo'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml'
        pathToSources: '$(System.DefaultWorkingDirectory)/app/src/main/java'
