---
trust-domain: mobile
treeherder:
    group-names:
        'I': 'Docker Image Builds'
        'Rap': 'Raptor tests'
        'Rap-P': 'Raptor power tests'

task-priority: lowest

taskgraph:
    register: rb_taskgraph:register
    repositories:
        mobile:
            name: "reference-browser"
    cached-task-prefix: project.mobile.reference-browser
    decision-parameters: 'rb_taskgraph:get_decision_parameters'

workers:
    aliases:
        b-android:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux'
        images:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'images'
        dep-signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type: mobile-t-signing
        signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type:
                by-level:
                    "3": mobile-3-signing
                    default: mobile-t-signing
        push-apk:
            provisioner: scriptworker-k8s
            implementation: scriptworker-pushapk
            os: scriptworker
            worker-type: 'mobile-{level}-pushapk'
        t-bitbar.*:
            provisioner: proj-autophone
            implementation: generic-worker
            os: linux-bitbar
            worker-type: 'gecko-{alias}'

scriptworker:
    scope-prefix: project:mobile:reference-browser:releng
