# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
    - rb_taskgraph.transforms.variant:transforms
    - rb_taskgraph.transforms.build_aab:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

job-defaults:
    description: Build AAB (Android App Bundle) from source code.
    treeherder:
        kind: build
        symbol: AAB
        tier: 2
    worker-type: b-android
    worker:
        docker-image: {in-tree: base}
        max-run-time: 7200
        chain-of-trust: true
    run:
        using: gradlew
        use-caches: false
    aab-artifact-template:
        type: file
        name: public/target.aab
        path: '/builds/worker/checkouts/src/app/build/outputs/bundle/{variant}/app-{variant}.aab'

jobs:
    nightly:
        attributes:
            nightly: true
        run-on-tasks-for: []
        include-nightly-version: true
        include-shippable-secrets: true
        run:
            gradlew: ["-PcrashReportEnabled=true", "-Ptelemetry=true", "bundleNightly"]
    debug:
        run-on-tasks-for: [github-push, github-pull-request]
        run:
            gradlew: ["bundleDebug"]
