default_platform(:android)

platform :android do
#   desc "Runs all the tests"
#   lane :test do
#     gradle(task: "test")
#   end
# 
#   desc "Submit a new Beta Build to Crashlytics Beta"
#   lane :beta do
#     gradle(task: "clean assembleRelease")
#     crashlytics
#   
#     # sh "your_script.sh"
#     # You can also use other beta testing services here
#   end
# 
#   desc "Deploy a new version to the Google Play"
#   lane :deploy do
#     gradle(task: "clean assembleRelease")
#     upload_to_play_store
#   end
    desc "Build Daisy"
    lane :build do
        gradle(
            task: "assemble",
            build_type: "Release",
            print_command: true,
            properties: {
                "versionName" => Time.now.strftime("%Y%m%d%H%M"),
                "android.injected.signing.store.file" => ENV["ANDROID_STORE_FILE"] || "",
                "android.injected.signing.store.password" => ENV["ANDROID_STORE_PWD"] || "",
                "android.injected.signing.key.alias" => ENV["ANDROID_KEY_ALIAS"] || "",
                "android.injected.signing.key.password" => ENV["ANDROID_KEY_PWD"] || "",
            }
        )
    end
end
